vlib work
vcom  Sines_pkg.vhd
vcom  DAC_Control.vhd
vcom  Subsystem.vhd
vcom  Subsystem10.vhd
vcom  Subsystem11.vhd
vcom  Subsystem12.vhd
vcom  Subsystem13.vhd
vcom  Subsystem14.vhd
vcom  Subsystem15.vhd
vcom  Subsystem16.vhd
vcom  Subsystem17.vhd
vcom  Subsystem18.vhd
vcom  Subsystem19.vhd
vcom  Subsystem2.vhd
vcom  Subsystem20.vhd
vcom  Subsystem3.vhd
vcom  Subsystem4.vhd
vcom  Subsystem5.vhd
vcom  Subsystem6.vhd
vcom  Subsystem7.vhd
vcom  Subsystem8.vhd
vcom  Subsystem9.vhd
vcom  Wrap_To_Zero.vhd
vcom  HEX0.vhd
vcom  Subsystem_block.vhd
vcom  Subsystem10_block.vhd
vcom  Subsystem11_block.vhd
vcom  Subsystem12_block.vhd
vcom  Subsystem13_block.vhd
vcom  Subsystem14_block.vhd
vcom  Subsystem15_block.vhd
vcom  Subsystem16_block.vhd
vcom  Subsystem17_block.vhd
vcom  Subsystem18_block.vhd
vcom  Subsystem19_block.vhd
vcom  Subsystem2_block.vhd
vcom  Subsystem20_block.vhd
vcom  Subsystem3_block.vhd
vcom  Subsystem4_block.vhd
vcom  Subsystem5_block.vhd
vcom  Subsystem6_block.vhd
vcom  Subsystem7_block.vhd
vcom  Subsystem8_block.vhd
vcom  Subsystem9_block.vhd
vcom  Wrap_To_Zero_block.vhd
vcom  HEX1.vhd
vcom  Subsystem_block1.vhd
vcom  Subsystem10_block1.vhd
vcom  Subsystem11_block1.vhd
vcom  Subsystem12_block1.vhd
vcom  Subsystem13_block1.vhd
vcom  Subsystem14_block1.vhd
vcom  Subsystem15_block1.vhd
vcom  Subsystem16_block1.vhd
vcom  Subsystem17_block1.vhd
vcom  Subsystem18_block1.vhd
vcom  Subsystem19_block1.vhd
vcom  Subsystem2_block1.vhd
vcom  Subsystem20_block1.vhd
vcom  Subsystem3_block1.vhd
vcom  Subsystem4_block1.vhd
vcom  Subsystem5_block1.vhd
vcom  Subsystem6_block1.vhd
vcom  Subsystem7_block1.vhd
vcom  Subsystem8_block1.vhd
vcom  Subsystem9_block1.vhd
vcom  Wrap_To_Zero_block1.vhd
vcom  HEX2.vhd
vcom  Subsystem_block2.vhd
vcom  Subsystem10_block2.vhd
vcom  Subsystem11_block2.vhd
vcom  Subsystem12_block2.vhd
vcom  Subsystem13_block2.vhd
vcom  Subsystem14_block2.vhd
vcom  Subsystem15_block2.vhd
vcom  Subsystem16_block2.vhd
vcom  Subsystem17_block2.vhd
vcom  Subsystem18_block2.vhd
vcom  Subsystem19_block2.vhd
vcom  Subsystem2_block2.vhd
vcom  Subsystem20_block2.vhd
vcom  Subsystem3_block2.vhd
vcom  Subsystem4_block2.vhd
vcom  Subsystem5_block2.vhd
vcom  Subsystem6_block2.vhd
vcom  Subsystem7_block2.vhd
vcom  Subsystem8_block2.vhd
vcom  Subsystem9_block2.vhd
vcom  Wrap_To_Zero_block2.vhd
vcom  HEX3.vhd
vcom  Subsystem10_block3.vhd
vcom  Subsystem11_block3.vhd
vcom  Subsystem12_block3.vhd
vcom  Subsystem13_block3.vhd
vcom  Subsystem8_block3.vhd
vcom  Subsystem9_block3.vhd
vcom  aPA_Save.vhd
vcom  Sin10.vhd
vcom  Sin11.vhd
vcom  Sin12.vhd
vcom  Sin13.vhd
vcom  Sin14.vhd
vcom  Sin15.vhd
vcom  Sin4.vhd
vcom  Sin5.vhd
vcom  Sin6.vhd
vcom  Sin7.vhd
vcom  Sin8.vhd
vcom  Sin9.vhd
vcom  Subsystem_block3.vhd
vcom  Subsystem1.vhd
vcom  Subsystem2_block3.vhd
vcom  Subsystem7_block3.vhd
vcom  Subsystem4_block3.vhd
vcom  Subsystem5_block3.vhd
vcom  Subsystem6_block3.vhd
vcom  Subsystem3_block3.vhd
vcom  Sines.vhd
