-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ThreeSines_DrSaher\Subsystem9_block3.vhd
-- Created: 2020-02-04 20:32:36
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem9_block3
-- Source Path: ThreeSines_DrSaher/Sines /Subsystem9
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem9_block3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        Enable                            :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(9 DOWNTO 0)  -- ufix10
        );
END Subsystem9_block3;


ARCHITECTURE rtl OF Subsystem9_block3 IS

  -- Signals
  SIGNAL enb_gated                        : std_logic;
  SIGNAL Enable_out2                      : std_logic;
  SIGNAL In1_unsigned                     : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL In1_bypass                       : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL In1_last_value                   : unsigned(9 DOWNTO 0);  -- ufix10

BEGIN
  Enable_out2 <= Enable;

  enb_gated <= Enable_out2 AND enb;

  In1_unsigned <= unsigned(In1);

  Out1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1_last_value <= to_unsigned(16#000#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        In1_last_value <= In1_bypass;
      END IF;
    END IF;
  END PROCESS Out1_bypass_process;


  
  In1_bypass <= In1_last_value WHEN Enable_out2 = '0' ELSE
      In1_unsigned;

  Out1 <= std_logic_vector(In1_bypass);

END rtl;

