-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ThreeSines_DrSaher\Subsystem13_block3.vhd
-- Created: 2021-03-10 22:43:26
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem13_block3
-- Source Path: ThreeSines_DrSaher/Sines /Subsystem13
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem13_block3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic;
        Enable                            :   IN    std_logic;
        Out1                              :   OUT   std_logic
        );
END Subsystem13_block3;


ARCHITECTURE rtl OF Subsystem13_block3 IS

  -- Signals
  SIGNAL enb_gated                        : std_logic;
  SIGNAL In1_hold                         : std_logic;

BEGIN
  enb_gated <= Enable AND enb;

  Out1_hold_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1_hold <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        In1_hold <= In1;
      END IF;
    END IF;
  END PROCESS Out1_hold_process;


  Out1 <= In1_hold;

END rtl;

