-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ThreeSines_DrSaher\Wrap_To_Zero_block1.vhd
-- Created: 2021-03-10 22:43:26
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Wrap_To_Zero_block1
-- Source Path: ThreeSines_DrSaher/Sines /HEX2/Wrap To Zero
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Wrap_To_Zero_block1 IS
  PORT( U                                 :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En11
        Y                                 :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En11
        );
END Wrap_To_Zero_block1;


ARCHITECTURE rtl OF Wrap_To_Zero_block1 IS

  -- Signals
  SIGNAL U_signed                         : signed(20 DOWNTO 0);  -- sfix21_En11
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : signed(20 DOWNTO 0);  -- sfix21_En11
  SIGNAL FixPt_Switch_out1                : signed(20 DOWNTO 0);  -- sfix21_En11

BEGIN
  -- U(k)

  U_signed <= signed(U);

  
  switch_compare_1 <= '1' WHEN U_signed > to_signed(16#004800#, 21) ELSE
      '0';

  Constant_out1 <= to_signed(16#000000#, 21);

  
  FixPt_Switch_out1 <= U_signed WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  Y <= std_logic_vector(FixPt_Switch_out1);


END rtl;

